import type { Metadata } from "next";
import "./globals.css";
import Header from "@/src/features/Header";
import Footer from "@/src/features/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`font-clashdisplay`}
      >
        <Header />
        {children}
        {/* Footer can be added here if needed */}
        <Footer />
      </body>
    </html>
  );
}
